docker compose change

diff --git a/docker/docker-compose.yml b/docker/docker-compose.yml
--- a/docker/docker-compose.yml
+++ b/docker/docker-compose.yml
@@ -1,226 +1,56 @@
-# Welcome to the Modern Data Lake.
-# Feel free to modify this file to suit your needs..
 ---
 version: '3'
 x-airflow-common:
   &airflow-common
-  # uncomment the image tag to use a specific image
-  # comment the build & context if you want to use the built image.
-  # image: 'air-prune'
-  build:
-    context: ./airflow-setup
+  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
+  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
+  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
+  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.3.2}
+  # build: .
   environment:
     &airflow-common-env
     AIRFLOW__CORE__EXECUTOR: CeleryExecutor
+    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
+    # For backward compatibility, with Airflow <2.3
     AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
     AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
     AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
     AIRFLOW__CORE__FERNET_KEY: ''
-    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
+    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
     AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
-    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
+    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
+    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:- praw boto3 configparser psycopg2-binary}
   volumes:
-    - ../dags:/opt/airflow/dags
-    - ../plugins:/opt/airflow/plugins
-    - ../logs:/opt/airflow/logs
-    - ../spark/app:/usr/local/spark/app 
-    - ../spark/resources:/usr/local/spark/resources 
-    - ../spark/conf:/spark/spark-3.2.0-bin-hadoop3.2/conf
-  user: "${AIRFLOW_UID:-50000}:$AIRFLOW_GID:-50000}"
-  env_file:
-    - .env
-  networks:
-    - oasiscorp
+    - ./dags:/opt/airflow/dags
+    - ./logs:/opt/airflow/logs
+    - ./plugins:/opt/airflow/plugins
+    - ./extraction:/opt/airflow/extraction
+    - $HOME/.aws/credentials:/home/airflow/.aws/credentials:ro
+  user: "${AIRFLOW_UID:-50000}:0"
   depends_on:
+    &airflow-common-depends-on
     redis:
       condition: service_healthy
     postgres:
       condition: service_healthy
 
 services:
-
-  # Postgre DB
   postgres:
-    hostname: oasispostgres
-    container_name: postgres_container
-    build:
-      context: ./postgres
-      dockerfile: Dockerfile
-    networks:
-     - oasiscorp
+    image: postgres:13
+    environment:
+      POSTGRES_USER: airflow
+      POSTGRES_PASSWORD: airflow
+      POSTGRES_DB: airflow
     volumes:
       - postgres-db-volume:/var/lib/postgresql/data
-      - ${PWD}/postgres/create_ranger_users.sql:/docker-entrypoint-initdb.d/create_ranger_users.sql
-    env_file:
-      - .env
-    ports:
-      - 5432:5432
     healthcheck:
       test: ["CMD", "pg_isready", "-U", "airflow"]
       interval: 5s
       retries: 5
     restart: always
-    
 
-  # Namenode: HDFS
-  namenode:
-      image: dimeji/hadoop-namenode:latest
-      container_name: hadoop-namenode
-      volumes:
-        - namenode:/hadoop/dfs/name
-      environment:
-        - CLUSTER_NAME=test
-      env_file:
-        - ${PWD}/hadoop-hive.env
-      ports:
-        - "50070:50070"
-      networks:
-        - oasiscorp
-
-  # Datanode: HDFS      
-  datanode:
-      image: dimeji/hadoop-datanode:latest
-      container_name: hadoop-datanode
-      volumes:
-        - datanode:/hadoop/dfs/data
-      env_file:
-        - ${PWD}/hadoop-hive.env
-      environment:
-        SERVICE_PRECONDITION: "namenode:50070"
-      ports:
-        - "50075:50075"
-      depends_on:
-      - namenode
-      networks:
-        - oasiscorp
-
-  # Hive: A Hive Metastore and a Hive Metastore Server
-  hive:
-      image: dimeji/hive-metastore
-      hostname: hive
-      container_name: hive-metastore
-      env_file:
-        - ${PWD}/hadoop-hive.env
-      command: /opt/hive/bin/hive --service metastore
-      environment:
-        SERVICE_PRECONDITION: "namenode:50070 datanode:50075 oasispostgres:5432"
-      ports:
-        - "9083:9083"
-      depends_on:
-        - namenode
-        - datanode
-      networks:
-        - oasiscorp
-      restart: on-failure
-
-      # /opt/hive/conf
-
-  # Hive Server: A Hive Metastore and a Hive Metastore Server    
-  hive-server:
-      image: dimeji/hive-server
-      container_name: hive-server
-      env_file:
-        - ${PWD}/hadoop-hive.env
-      environment:
-        HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive/metastore"
-        SERVICE_PRECONDITION: "hive:9083"
-      ports:
-        - "10000:10000"
-      depends_on:
-        - hive
-      networks:
-        - oasiscorp
-
-
-  # Jupyter notebook
-  jupyter-spark:
-        hostname: myjupyter
-        container_name: jupyter_container
-        image: 'jupyter/pyspark-notebook:spark-3.2.0'
-        networks:
-            - oasiscorp
-        ports:
-          - "8888:8888"
-        volumes:
-          - ../notebooks:/home/jovyan/work/notebooks/
-          - ../spark/resources/data:/home/jovyan/work/data/
-          - ../spark/resources/jars:/home/jovyan/work/jars/
-          - ../spark/conf:/usr/local/spark/conf
-        restart: always
-        depends_on:
-                - postgres
-
-
-  # # Zookeeper: A configuration Manager for NiFi
-  # zookeeper:
-  #       hostname: myzookeeper
-  #       container_name: zookeeper_container
-  #       image: 'bitnami/zookeeper:3.7.0'  # latest image as of 2021-11-08.
-  #       environment:
-  #           - ALLOW_ANONYMOUS_LOGIN=yes
-  #       networks:
-  #           - oasiscorp
-  #       restart: always
-
-  # # Apache Nifi: Data extraction, Transformation and load service.
-  # nifi:
-  #       hostname: mynifi
-  #       container_name: nifi_container
-  #       image: 'apache/nifi:1.15.0'  # latest image as of 2021-11-08.
-  #       ports:
-  #           - '8091:8080'
-  #       networks:
-  #           - oasiscorp
-  #       volumes:
-  #           - nifi-database_repository:/opt/nifi/nifi-current/database_repository
-  #           - nifi-flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
-  #           - nifi-content_repository:/opt/nifi/nifi-current/content_repository
-  #           - nifi-provenance_repository:/opt/nifi/nifi-current/provenance_repository
-  #           - nifi-conf:/opt/nifi/nifi-current/conf
-  #           - nifi-state:/opt/nifi/nifi-current/state
-  #           - ../nifi/logs:/opt/nifi/nifi-current/logs
-  #           - ../nifi/jdbc:/opt/nifi/nifi-current/jdbc
-  #           - ../nifi/credentials:/opt/nifi/nifi-current/credentials
-  #       env_file:
-  #           - ./.env
-  #       restart: on-failure
-  #       healthcheck:
-  #           test: ["CMD", "curl", "-f", "http://mynifi:8080/nifi/"]
-  #           interval: 30s
-  #           timeout: 20s
-  #           retries: 3
-
-  # # Nifi-Registry: Version control for Nifi Flows.
-  # registry:
-  #       hostname: myregistry
-  #       container_name: registry_container
-  #       image: 'apache/nifi-registry:latest'  
-  #       restart: always
-  #       ports:
-  #           - "18080:18080"
-  #       environment:
-  #           - LOG_LEVEL=INFO
-  #           - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
-  #           - NIFI_REGISTRY_FLOW_PROVIDER=file
-  #           - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
-  #       volumes:
-  #           - ../nifi_registry/database:/opt/nifi-registry/nifi-registry-current/database
-  #           - ../nifi_registry/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
-  #       networks:
-  #           - oasiscorp
-  #       healthcheck:
-  #           test: ["CMD", "curl", "-f", "http://myregistry:18080/nifi-registry/"]
-  #           interval: 30s
-  #           timeout: 20s
-  #           retries: 3
-
-
-  # Redis DB
   redis:
-    image: 'redis:latest'
-    container_name: redis
-    networks:
-      - oasiscorp
+    image: redis:latest
     expose:
       - 6379
     healthcheck:
@@ -230,56 +60,182 @@ services:
       retries: 50
     restart: always
 
-  # Airflow Web UI
   airflow-webserver:
     <<: *airflow-common
     command: webserver
-    container_name: webserver
     ports:
-        - '8085:8080'
+      - 8080:8080
     healthcheck:
-      test: ["CMD", "curl", "--fail", "http://localhost:8085/health"]
+      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
       interval: 10s
       timeout: 10s
       retries: 5
     restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
 
-  # Airflow Scheduler
   airflow-scheduler:
     <<: *airflow-common
     command: scheduler
-    container_name: scheduler
+    healthcheck:
+      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
+      interval: 10s
+      timeout: 10s
+      retries: 5
     restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
 
-  # Airflow Worker 
   airflow-worker:
     <<: *airflow-common
     command: celery worker
-    container_name: celery-worker
+    healthcheck:
+      test:
+        - "CMD-SHELL"
+        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    environment:
+      <<: *airflow-common-env
+      # Required to handle warm shutdown of the celery workers properly
+      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
+      DUMB_INIT_SETSID: "0"
     restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
 
-  # Airflow DB
+  airflow-triggerer:
+    <<: *airflow-common
+    command: triggerer
+    healthcheck:
+      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
   airflow-init:
     <<: *airflow-common
-    command: version
-    container_name: airflow-init
+    entrypoint: /bin/bash
+    # yamllint disable rule:line-length
+    command:
+      - -c
+      - |
+        function ver() {
+          printf "%04d%04d%04d%04d" $${1//./ }
+        }
+        airflow_version=$$(gosu airflow airflow version)
+        airflow_version_comparable=$$(ver $${airflow_version})
+        min_airflow_version=2.2.0
+        min_airflow_version_comparable=$$(ver $${min_airflow_version})
+        if (( airflow_version_comparable < min_airflow_version_comparable )); then
+          echo
+          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+          echo
+          exit 1
+        fi
+        if [[ -z "${AIRFLOW_UID}" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
+          echo "If you are on Linux, you SHOULD follow the instructions below to set "
+          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
+          echo "For other operating systems you can get rid of the warning with manually created .env file:"
+          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#setting-the-right-airflow-user"
+          echo
+        fi
+        one_meg=1048576
+        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+        warning_resources="false"
+        if (( mem_available < 4000 )) ; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
+          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
+          echo
+          warning_resources="true"
+        fi
+        if (( cpus_available < 2 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
+          echo "At least 2 CPUs recommended. You have $${cpus_available}"
+          echo
+          warning_resources="true"
+        fi
+        if (( disk_available < one_meg * 10 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
+          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
+          echo
+          warning_resources="true"
+        fi
+        if [[ $${warning_resources} == "true" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
+          echo "Please follow the instructions to increase amount of resources available:"
+          echo "   https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#before-you-begin"
+          echo
+        fi
+        mkdir -p /sources/logs /sources/dags /sources/plugins
+        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
+        exec /entrypoint airflow version
+    # yamllint enable rule:line-length
     environment:
       <<: *airflow-common-env
       _AIRFLOW_DB_UPGRADE: 'true'
       _AIRFLOW_WWW_USER_CREATE: 'true'
       _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
       _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
+      _PIP_ADDITIONAL_REQUIREMENTS: ''
+    user: "0:0"
+    volumes:
+      - .:/sources
 
+  airflow-cli:
+    <<: *airflow-common
+    profiles:
+      - debug
+    environment:
+      <<: *airflow-common-env
+      CONNECTION_CHECK_MAX_COUNT: "0"
+    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
+    command:
+      - bash
+      - -c
+      - airflow
 
+  # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
+  # or by explicitly targeted on the command line e.g. docker-compose up flower.
+  # See: https://docs.docker.com/compose/profiles/
+  flower:
+    <<: *airflow-common
+    command: celery flower
+    profiles:
+      - flower
+    ports:
+      - 5555:5555
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
 
-# Volumes 
 volumes:
   postgres-db-volume:
-  namenode:
-  datanode:
-
-
-# Network Bridge Connection
-networks:
-  oasiscorp:
-    driver: bridge
